# Plotting with querying

## TimeSeries

In [27]:
import os
import Querying as Q
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import hvplot.pandas

ModuleNotFoundError: No module named 'hvplot'

In [15]:
path = 'D:\\Repos\\PirnaCaseStudy\\Database'
database_fn = 'Database.db'
database_path = path + '\\' + database_fn

In [19]:
x = Q.TimeSeries(database_path, 0, 0)
dfX = x.DataFrame

y = Q.PotentiometricMap(database_path, filterVariable = 0, Year = 2015, Month = 1, Day = 30, FilterHour = 12)
dfY= y.DataFrame

z = Q.HydroProfile(database_path, 0)
dfZ= z.DataFrame

 ******************** DataFrame already generated **********************





 ******************** DataFrame already generated **********************





 ******************** DataFrame already generated **********************

In [26]:
z = Q.HydroProfile(database_path, 3)
dfZ= z.DataFrame

            SELECT
            	HydroTests.ID, HydroTests.DrillID, HydroTests.TestTypeID, HydroTests.Depth, HydroTests.Value,
            	TestsType.ID, TestsType.Unit, TestsType.Name, TestsType.Variable,
            	Drills.ID, Drills.Name, Drills.Depth, Drills.Well, Drills.E, Drills.N

            FROM
            	HydroTests
            JOIN
            	TestsType ON HydroTests.TestTypeID = TestsType.ID
            JOIN
            	Drills ON HydroTests.DrillID = Drills.ID
            WHERE
            	DrillID = 3

In [22]:
dfZ

,DrillID,Depth,Unit,Name,Variable,Value,ID,Name,Depth,E,N
0,1,0.000,mS/cm,EC logs,EC,1.02,1,D-G02,14.0,13.922918,50.96582
1,1,0.015,mS/cm,EC logs,EC,1.01,1,D-G02,14.0,13.922918,50.96582
2,1,0.030,mS/cm,EC logs,EC,1.01,1,D-G02,14.0,13.922918,50.96582
3,1,0.046,mS/cm,EC logs,EC,1.0,1,D-G02,14.0,13.922918,50.96582
4,1,0.061,mS/cm,EC logs,EC,1.0,1,D-G02,14.0,13.922918,50.96582
...,...,...,...,...,...,...,...,...,...,...,...
986,1,14.188,mS/cm,EC logs,EC,6.0,1,D-G02,14.0,13.922918,50.96582
987,1,14.204,mS/cm,EC logs,EC,6.0,1,D-G02,14.0,13.922918,50.96582
988,1,14.219,mS/cm,EC logs,EC,6.5,1,D-G02,14.0,13.922918,50.96582
989,1,14.234,mS/cm,EC logs,EC,6.25,1,D-G02,14.0,13.922918,50.96582
990,1,14.249,mS/cm,EC logs,EC,6.63,1,D-G02,14.0,13.922918,50.96582